name: femo
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=1.0
  - blosc=1.21.2
  - boost-cpp=1.74.0
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.3.11
  - cffi=1.16.0
  - fenics-basix=0.5.0
  - fenics-dolfinx=0.5.1
  - fenics-ffcx=0.5.0
  - fenics-libbasix=0.5.0
  - fenics-libdolfinx=0.5.1
  - fenics-ufcx=0.5.0
  - fenics-ufl=2022.2.0
  - fftw=3.3.10
  - gmp=6.2.1
  - hdf5=1.12.1
  - hypre=2.25.0
  - icu=70.1
  - krb5=1.20.1
  - libadios2=2.8.3
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.1.2
  - libcxx=14.0.6
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.4
  - libgfortran=5.0.0 # Error with doc build
  - libgfortran5=13.2.0
  - liblapack=3.9.0
  - libnghttp2=1.52.0
  - libopenblas=0.3.27
  - libpng=1.6.43
  - libsodium=1.0.18
  - libssh2=1.11.0
  - libzlib=1.2.13
  - llvm-openmp=18.1.3
  - lz4-c=1.9.4
  - metis=5.1.0
  - mpfr=4.2.1
  - mpi=1.0
  - mpi4py=3.1.4
  - mumps-include=5.2.1
  - mumps-mpi=5.2.1
  - ncurses=6.4
  - numpy=1.24.2
  - openmpi=4.1.5
  - openssl=3.2.1
  - parmetis=4.0.3
  - petsc=3.17.3
  - petsc4py=3.17.3
  - pip=23.3.1
  - ptscotch=6.0.9
  - pugixml=1.11.4
  - pybind11-abi=4
  - pycparser=2.22
  - python=3.9.18
  - python_abi=3.9
  - readline=8.2
  - scalapack=2.2.0
  - scotch=6.0.9
  - setuptools=68.2.2
  - slepc=3.17.1
  - slepc4py=3.17.1
  - snappy=1.1.10
  - sqlite=3.41.2
  - suitesparse=5.10.1
  - superlu=5.2.2
  - superlu_dist=7.2.0
  - tbb=2021.10.0
  - tk=8.6.12
  - wheel=0.41.2
  - xtensor=0.24.6
  - xtl=0.7.5
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zfp=0.5.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - alabaster==0.7.16
      - alembic==1.13.2
      - appdirs==1.4.4
      - appnope==0.1.4
      - array-manager==0.1
      - astroid==2.15.5
      - asttokens==2.4.1
      - attrs==23.2.0
      - babel==2.14.0
      - backports-tarfile==1.0.0
      - caddee-materials==0.0.1
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - colorcet==3.1.0
      - colorlog==6.8.2
      - comm==0.2.2
      - contourpy==1.2.1
      - csdl==0.0.0
      - csdl-alpha==0.0.0a2
      - cycler==0.12.1
      - cython==0.29.28
      - debugpy==1.8.1
      - decorator==5.1.1
      - docutils==0.17.1
      - exceptiongroup==1.2.0
      - executing==2.0.1
      - fastjsonschema==2.19.1
      - filelock==3.15.4
      - flexcache==0.3
      - flexparser==0.3.1
      - fonttools==4.51.0
      - fsspec==2024.6.1
      - gitdb==4.0.11
      - gitpython==3.1.43
      - greenlet==3.0.3
      - guppy3==3.1.4.post1
      - h5py==3.10.0
      - idna==3.7
      - imagesize==1.4.1
      - importlib-metadata==7.1.0
      - importlib-resources==6.4.0
      - iniconfig==2.0.0
      - ipykernel==6.29.4
      - ipython==8.18.1
      - jaraco-classes==3.4.0
      - jaraco-context==5.3.0
      - jaraco-functools==4.0.0
      - jedi==0.19.1
      - jinja2==3.1.3
      - joblib==1.4.2
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - jupyter-cache==1.0.0
      - jupyter-client==8.6.1
      - jupyter-core==5.7.2
      - keyring==25.1.0
      - kiwisolver==1.4.5
      - latexcodec==3.0.0
      - lazy-object-proxy==1.10.0
      - lxml==5.2.2
      - mako==1.3.5
      - markdown-it-py==2.2.0
      - markupsafe==2.1.5
      - matplotlib==3.8.4
      - matplotlib-inline==0.1.7
      - mdit-py-plugins==0.3.5
      - mdurl==0.1.2
      - meshio==5.3.5
      - modopt==0.1.0
      - more-itertools==10.2.0
      - mpmath==1.3.0
      - myst-nb==1.1.0
      - myst-parser==1.0.0
      - nbclient==0.10.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - nh3==0.2.17
      - numpydoc==1.6.0
      - optuna==3.6.1
      - packaging==24.0
      - pandas==2.2.2
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==10.3.0
      - pint==0.24.1
      - pipdate==0.3.5
      - pkginfo==1.10.0
      - platformdirs==4.2.0
      - pluggy==1.4.0
      - prompt-toolkit==3.0.43
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pybtex==0.24.0
      - pybtex-docutils==1.0.3
      - pydot==2.0.0
      - pygments==2.17.2
      - pyparsing==3.1.2
      - pytest==8.1.1
      - python-csdl-backend==0.0.0
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyyaml==6.0.1
      - pyzmq==26.0.0
      - readme-renderer==43.0
      - referencing==0.34.0
      - requests==2.31.0
      - requests-toolbelt==1.0.0
      - rfc3986==2.0.0
      - rich==13.7.1
      - rpds-py==0.18.0
      - rustworkx==0.14.2
      - scikit-learn==1.5.0
      - scipy==1.10.1
      - six==1.16.0
      - smmap==5.0.1
      - snowballstemmer==2.2.0
      - sphinx==5.3.0
      - sphinx-autoapi==2.1.0
      - sphinx-copybutton==0.5.2
      - sphinx-rtd-theme==2.0.0
      - sphinxcontrib-applehelp==1.0.8
      - sphinxcontrib-bibtex==2.6.2
      - sphinxcontrib-collections==0.0.2
      - sphinxcontrib-devhelp==1.0.6
      - sphinxcontrib-htmlhelp==2.0.5
      - sphinxcontrib-jquery==4.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.7
      - sphinxcontrib-serializinghtml==1.1.10
      - sqlalchemy==2.0.29
      - stack-data==0.6.3
      - sympy==1.12
      - tabulate==0.9.0
      - threadpoolctl==3.5.0
      - tomli==2.0.1
      - torch==2.2.2
      - tornado==6.4
      - tqdm==4.66.4
      - traitlets==5.14.2
      - twine==5.0.0
      - typing-extensions==4.11.0
      - tzdata==2024.1
      - unidecode==1.3.8
      - urllib3==2.2.1
      - vedo==2024.5.1
      - vtk==9.3.0
      - wcwidth==0.2.13
      - wrapt==1.16.0
      - zipp==3.18.1
